export const assetAttributions: { file: string; source: string; author: string; license: string; url: string }[] = [
  // === KATEGORI 1 — HERO & JEDA JIWA ===
  { file: "hero/video/animal.mp4", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "Proprietary", url: "" },
  { file: "hero/video/culture.mp4", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "Proprietary", url: "" },
  { file: "hero/video/nature.mp4", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "Proprietary", url: "" },
  { file: "images/eksplorasi/kei-sunset-jeda.jpg", source: "Wikimedia Commons", author: "Miranda Rachellina", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Sunset_At_Ngurbloat_Beach.jpg" },
  { file: "images/og/simfoni-evav-og.jpg", source: "Wikimedia Commons", author: "Miranda Rachellina", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Clouds_At_Ngurbloat.jpg" },

  // === KATEGORI 2 — BUDAYA (aset original / Unsplash) ===
  { file: "images/budaya/kei_batik.png", source: "Unsplash (representative / ilustratif)", author: "Unsplash", license: "Unsplash License (bebas, ilustratif)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_coast_sunset.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_dada_tifa.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_language_symbol.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/landmark_langgur_kei_larvul_spear.jpeg", source: "RRI (rri.co.id)", author: "RRI", license: "Editorial / Hak cipta RRI (dipakai dengan atribusi)", url: "https://rri.co.id" },
  { file: "images/budaya/kei_busana_adat.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_rule_tanah.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/budaya/kei_warriors_dance.png", source: "Unsplash (representative / ilustratif)", author: "Unsplash", license: "Unsplash License (bebas, ilustratif)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/tenun_elat_watermark.svg", source: "Original (AI-generated / synthetic)", author: "Simfoni Evav", license: "CC0", url: "" },

  // === KATEGORI 2B — BUDAYA (aset web eksternal, format title-credit) ===
  { file: "images/budaya/festival-meti-pinterest-cherryll.png", source: "Pinterest", author: "Cherryll", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://www.pinterest.com/" },
  { file: "images/budaya/festival-pesona-meti-kei-2025-triptrus.jpg", source: "Triptrus", author: "Triptrus", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://www.triptrus.com/" },
  { file: "images/budaya/lomba-perahu-belan-rri.jpg", source: "RRI (rri.co.id)", author: "RRI", license: "Editorial / Hak cipta RRI (dipakai dengan atribusi)", url: "https://rri.co.id" },
  { file: "images/budaya/masyarakat-kei-thespiceroute.jpg", source: "The Spice Route", author: "The Spice Route", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://thespiceroute.end.com/" },
  { file: "images/budaya/pembuatan-embal-umkm.jpg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/budaya/ritual-penyambutan-tamu-rinin.jpg", source: "Fotografer Kei (Original)", author: "Simfoni Evav", license: "CC BY (lokal)", url: "" },
  { file: "images/budaya/suku-tanimbar-tropenmuseum.jpg", source: "Tropenmuseum (Wikimedia Commons)", author: "Tropenmuseum", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/budaya/sumpah-adat-kei-infopublik.png", source: "Info Publik", author: "Info Publik", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://infopublik.id/" },
  { file: "images/budaya/tari-perang-kompasiana.jpg", source: "Kompasiana", author: "Kompasiana", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://www.kompasiana.com/" },
  { file: "images/budaya/tari-sawat-infopublik.jpg", source: "Info Publik", author: "Info Publik", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://infopublik.id/" },
  { file: "images/budaya/tari-syariat-kemdikbud.png", source: "Kementerian Kebudayaan (Indonesia)", author: "Kemdikbud", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://kebudayaan.kemdikbud.go.id/" },
  { file: "images/budaya/belis-mas-kawin.png", source: "Fotografer Kei (Original)", author: "Simfoni Evav", license: "CC BY (lokal)", url: "" },
  { file: "images/budaya/jejak-islam-masjid-ohoitom-tahayad.png", source: "Fotografer Kei (Original)", author: "Simfoni Evav", license: "CC BY (lokal)", url: "" },
  { file: "images/budaya/kei-busana-adat-arnol-arnol-pinterest.png", source: "Pinterest", author: "Arnol Arnol", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://www.pinterest.com/" },
  { file: "images/budaya/tenun-ikat-elat-kompas.png", source: "Kompasiana", author: "Kompasiana", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://www.kompasiana.com/" },
  { file: "images/budaya/kei_gong_dada_ilustration.jpeg", source: "Wikimedia Commons", author: "Wikimedia user (ilustrasi)", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/budaya/perahu_belan_race_kei.png", source: "Gemini Image Generator", author: "Simfoni Evav (AI Generated)", license: "CC BY (lokal)", url: "" },
  // === KATEGORI 3 — HERITAGE & SEJARAH ===
  { file: "images/heritage/kampung_debut.jpeg", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/heritage/kampung-selayar-.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/heritage/karel_monument_tragedy.jpeg", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/heritage/karel-sadsuitubun-airport-wikipedia.jpg", source: "Wikimedia Commons", author: "Wikimedia user", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/heritage/karel_street.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/heritage/kriel_356.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/heritage/napak-tilas-pengangkatan-raja.jpeg", source: "Fotografer Kei (Original)", author: "Simfoni Evav", license: "CC BY (lokal)", url: "" },
  { file: "images/heritage/napak-tilas-pengangkatan-raja-2.jpeg", source: "Fotografer Kei (Original)", author: "Simfoni Evav", license: "CC BY (lokal)", url: "" },
  { file: "images/heritage/raja-kei.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/heritage/foto-formal-karel-sadsuitubun.png", source: "Wikimedia Commons", author: "Wikimedia user", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/heritage/raja-raja-rat.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },

  // === KATEGORI 4 — EKSPLORASI / METI KEI ===
  { file: "images/eksplorasi/wer_warat_custom.png", source: "Gemini Image Generator", author: "Simfoni Evav (AI Generated)", license: "CC BY (lokal)", url: "" },
  { file: "images/eksplorasi/kei_waving.png", source: "Unsplash", author: "Sean O. (Unsplash)", license: "Unsplash License (free)", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e" },
  { file: "images/eksplorasi/kei_bair.jpg", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/eksplorasi/kei_beach.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/eksplorasi/kei_hawang.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/eksplorasi/kei_ngurbloat.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/eksplorasi/kei_ngurtavur.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/eksplorasi/kei_resort.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/eksplorasi/kei_mosaic_1.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/eksplorasi/kei_night_stars.png", source: "Wikimedia Commons", author: "Wikimedia user", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/eksplorasi/pantai-kelapa-miring.jpg", source: "Fotografer Kei (Original)", author: "Simfoni Evav", license: "CC BY (lokal)", url: "" },
  { file: "images/eksplorasi/pelikan_migration_australia.png", source: "Gemini Image Generator", author: "Simfoni Evav (AI Generated)", license: "CC BY (lokal)", url: "" },

  // === KATEGORI 4B — EKSPLORASI (aset web eksternal, format title-credit) ===
  { file: "images/eksplorasi/desa-wisata-ngilngof-antara.jpg", source: "Antara Megapolitan News", author: "Antara", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://megapolitan.news/" },
  { file: "images/eksplorasi/desa-wisata-ngilngof-candra-gunawan.jpg", source: "GoKepri (Candra Gunawan)", author: "Candra Gunawan", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://gokepri.com/" },
  { file: "images/eksplorasi/goa-hawang-2-bona-arifin.jpg", source: "Pinterest", author: "Bona Arifin", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://www.pinterest.com/" },
  { file: "images/eksplorasi/goa-hawang.jpg", source: "Fotografer Kei (Original)", author: "Simfoni Evav", license: "CC BY (lokal)", url: "" },
  { file: "images/eksplorasi/pantai-ngurbloat-tukang-jalan.jpg", source: "Tukang Jalan", author: "Tukang Jalan", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://tukangjalan.com/" },
  { file: "images/eksplorasi/pantai-pasir-panjang-ilhamarch.jpg", source: "Pinterest", author: "@ilhamarch", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://www.pinterest.com/" },
  { file: "images/eksplorasi/pulau-bair-rizkipambudi.jpg", source: "Instagram", author: "@rizkipambudi", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://www.instagram.com/" },
  { file: "images/eksplorasi/snorkeling-ngurtavur-zanzztoy.jpg", source: "Pinterest", author: "@zanzztoy", license: "Hak cipta pihak ketiga (dipakai dengan atribusi)", url: "https://www.pinterest.com/" },
  { file: "images/eksplorasi/spot-eka-bagus-2-kkn-ugm.jpg", source: "KKN UGM", author: "KKN UGM (Eka Bagus)", license: "CC BY (lokal)", url: "https://ugm.ac.id/" },
  { file: "images/eksplorasi/spot-eka-bagus-3-kkn-ugm.jpg", source: "KKN UGM", author: "KKN UGM (Eka Bagus)", license: "CC BY (lokal)", url: "https://ugm.ac.id/" },
  { file: "images/eksplorasi/spot-eka-bagus-kkn-ugm.png", source: "KKN UGM", author: "KKN UGM (Eka Bagus)", license: "CC BY (lokal)", url: "https://ugm.ac.id/" },

  // === KATEGORI 5 — KULINER & UMKM ===
  { file: "images/kuliner/kei_culinary_enbal.png", source: "Unsplash (representative / ilustratif)", author: "Unsplash", license: "Unsplash License (bebas, ilustratif)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_culinary_fish.png", source: "Unsplash (representative / ilustratif)", author: "Unsplash", license: "Unsplash License (bebas, ilustratif)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_culinary_sirsir.png", source: "Unsplash (representative / ilustratif)", author: "Unsplash", license: "Unsplash License (bebas, ilustratif)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_food_atmosfer.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_pisang_enbal.png", source: "Unsplash (representative / ilustratif)", author: "Unsplash", license: "Unsplash License (bebas, ilustratif)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_ikan_colocolo.png", source: "Unsplash (representative / ilustratif)", author: "Unsplash", license: "Unsplash License (bebas, ilustratif)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_lat.png", source: "Unsplash (representative / ilustratif)", author: "Unsplash", license: "Unsplash License (bebas, ilustratif)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_sagu.jpg", source: "Unsplash (representative / ilustratif)", author: "Unsplash", license: "Unsplash License (bebas, ilustratif)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_umkm_enbal_bunga_1.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_enbal_bunga_2.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_enbal_crispy_rumput_laut.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_enbal_kacang_1.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_enbal_kacang_2.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_enbal_stick_1.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_enbal_stick_2.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_enbal_stick_3.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_kacang_botol_1.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_kacang_botol_2.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_kerupuk_enbal_super.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_kue_kering_mocaf_makmur_1.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_kue_kering_mocaf_makmur_2.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_kue_kering_mocaf_saleha.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_piece_enbal.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umkm_tepung_mocaf.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/kuliner/kei_umbi_santan.png", source: "Gemini Image Generator", author: "Simfoni Evav (AI Generated)", license: "CC BY (lokal)", url: "" },

  // === KATEGORI 6 — SATWA & ALAM ===
  { file: "images/satwa/kei_underwater.png", source: "Wikimedia Commons", author: "Wikimedia user (Moore Reef underwater ReefScape)", license: "CC BY-SA", url: "https://commons.wikimedia.org/wiki/File:Moore_Reef_underwater_ReefScape.jpg" },
  { file: "images/satwa/kei_dolphin.png", source: "Wikimedia Commons", author: "Wikimedia user (Tursiops truncatus 01)", license: "CC BY-SA", url: "https://commons.wikimedia.org/wiki/File:Tursiops_truncatus_01.jpg" },
  { file: "images/satwa/kei_mangrove.png", source: "Gemini Image Generator", author: "Simfoni Evav (AI Generated)", license: "CC BY (lokal)", url: "" },
  { file: "images/satwa/kei_coral.png", source: "Wikimedia Commons", author: "Wikimedia user", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/satwa/kei_seaturtle.png", source: "Wikimedia Commons", author: "Wikimedia user", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/satwa/kei_bubut.png", source: "Wikimedia Commons", author: "Wikimedia user", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/satwa/kei_kacamata_bird.png", source: "Wikimedia Commons", author: "Wikimedia user", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/satwa/kei_kakatua.png", source: "Wikimedia Commons", author: "Wikimedia user", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/satwa/kei_kangguru.png", source: "Wikimedia Commons", author: "Wikimedia user", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/satwa/kei_elang.png", source: "Wikimedia Commons", author: "Wikimedia user", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/satwa/kei_kuskus.png", source: "Gemini Image Generator", author: "Simfoni Evav (AI Generated)", license: "CC BY (lokal)", url: "" },
  // === KATEGORI 7 — TEKNOLOGI ===
  { file: "images/teknologi/kei_technology_hawear.png", source: "Unsplash (representative / ilustratif)", author: "Unsplash", license: "Unsplash License (bebas, ilustratif)", url: "https://images.unsplash.com/" },
  { file: "images/teknologi/kei_technology_meti.png", source: "Unsplash (representative / ilustratif)", author: "Unsplash", license: "Unsplash License (bebas, ilustratif)", url: "https://images.unsplash.com/" },
  { file: "images/teknologi/kei_technology_sasi.png", source: "Unsplash (representative / ilustratif)", author: "Unsplash", license: "Unsplash License (bebas, ilustratif)", url: "https://images.unsplash.com/" },

  // === KATEGORI 2C — VIDEO EKSPRESI BUDAYA ===
  { file: "videos/tari-belan.mp4", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC BY (lokal)", url: "" },

  // === KATEGORI 8 — AUDIO, OG & IKON BRAND ===
  { file: "sounds/kei-waves.webm", source: "Freesound", author: "dobroide", license: "CC0 1.0 (public domain)", url: "https://freesound.org/people/dobroide/sounds/93647/" },
  { file: "images/og/simfoni-evav-og.jpg", source: "Unsplash", author: "kian zhang", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "kapal.svg", source: "Original (AI-generated / synthetic)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "logo-black.svg", source: "Original (brand)", author: "Simfoni Evav", license: "Proprietary", url: "" },
  { file: "logo-color.svg", source: "Original (brand)", author: "Simfoni Evav", license: "Proprietary", url: "" },
  { file: "logo-white.svg", source: "Original (brand)", author: "Simfoni Evav", license: "Proprietary", url: "" },
  { file: "maatahari.svg", source: "Original (AI-generated / synthetic)", author: "Simfoni Evav", license: "CC0", url: "" },
];
