export const assetAttributions: { file: string; source: string; author: string; license: string; url: string }[] = [
  // === KATEGORI 1 — HERO & JEDA JIWA ===
  { file: "hero/video/animal.mp4", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "Proprietary", url: "" },
  { file: "hero/video/culture.mp4", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "Proprietary", url: "" },
  { file: "hero/video/nature.mp4", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "Proprietary", url: "" },
  { file: "images/meti/kei-sunset-jeda.jpg", source: "Wikimedia Commons", author: "Miranda Rachellina", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Sunset_At_Ngurbloat_Beach.jpg" },
  { file: "images/og/simfoni-evav-og.jpg", source: "Wikimedia Commons", author: "Miranda Rachellina", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Clouds_At_Ngurbloat.jpg" },

  // === KATEGORI 2 — BUDAYA, HERITAGE & SEJARAH ===
  { file: "images/budaya/kei_batik.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_people_portrait.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_coast_sunset.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_culture.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_culture_ritual.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_dada_tifa.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_language_symbol.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_larvul_spear.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_meti_reef.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_busana_adat.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_rule_damai.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/budaya/kei_rule_harta.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/budaya/kei_rule_kehormatan.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/budaya/kei_rule_kekerasan.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/budaya/kei_rule_keluarga.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/budaya/kei_rule_sumpah.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/budaya/kei_rule_tanah.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/budaya/kei_tanimbar.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_tari_sawat_1.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_tari_sawat_2.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_tari_sawat_3.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_umkm_face_1.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_umkm_face_2.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_umkm_face_3.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/kei_warriors_dance.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/budaya/tenun_elat_watermark.svg", source: "Original (generated)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/heritage/ohoi_rumadian.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/heritage/ohoi_tel_nangan.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/heritage/elang_kecil.png", source: "Wikimedia Commons", author: "Wikimedia user (Cenderawasih)", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/heritage/evav_legacy.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/heritage/gong_dada_wadlau.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/heritage/kampung_debut.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/heritage/kampung_lairngaggas.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/heritage/kampung_selayar.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/heritage/kampung_namar.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/heritage/kampung_ngilngof.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/heritage/kampung_ngayub.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/heritage/kampung_ohoiluk.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/heritage/karel_airport.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/heritage/karel_formal_portrait.png", source: "Unsplash (representative stock)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/heritage/karel_monument.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/heritage/karel_monument_tragedy.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/heritage/karel_portrait.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/heritage/karel_rumadian.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/heritage/karel_street.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/heritage/kei_night_stars.png", source: "Wikimedia Commons", author: "Wikimedia user", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/heritage/kei_warriors_dance.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/heritage/kriel_356.png", source: "Original (Simfoni Evav)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "images/heritage/napak-tilas-pengangkatan-raja.jpeg", source: "Fotografer Kei (Original)", author: "Simfoni Evav", license: "CC BY (lokal)", url: "" },
  { file: "images/heritage/napak-tilas-pengangkatan-raja-2.jpeg", source: "Fotografer Kei (Original)", author: "Simfoni Evav", license: "CC BY (lokal)", url: "" },
  { file: "images/sejarah/arsip_monumen.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/sejarah/arsip_koperasi.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },

  // === KATEGORI 3 — EKSPLORASI / METI KEI ===
  { file: "images/meti/wer_warat.png", source: "Unsplash", author: "Sean O. (Unsplash)", license: "Unsplash License (free)", url: "https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6" },
  { file: "images/meti/perahu_belan.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/photo-1505159940484-eb2b9f2588e2" },
  { file: "images/meti/kei_waving.png", source: "Unsplash", author: "Sean O. (Unsplash)", license: "Unsplash License (free)", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e" },
  { file: "images/meti/kei_bair.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/meti/kei_beach.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/meti/kei_hawang.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/meti/kei_ngurbloat.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/meti/kei_ngurtavur.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/meti/kei_resort.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/meti/kei_snorkeling.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/eksplorasi/pasir_panjang.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/photo-1505881502353-a1986add3762" },
  { file: "images/eksplorasi/ohoiluk_gua.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/photo-1503551723145-6c040742065b" },
  { file: "images/eksplorasi/viewpoint_bukit.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368" },
  { file: "images/eksplorasi/snorkeling_ngurtavur.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5" },
  { file: "images/eksplorasi/pulau_tersembunyi.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/photo-1540202404-a2f29016b523" },
  { file: "images/eksplorasi/gua_hawang_inner.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/photo-1530841377377-3ff06c0ca713" },
  { file: "images/eksplorasi/pantai-kelapa-miring.jpeg", source: "Fotografer Kei (Original)", author: "Simfoni Evav", license: "CC BY (lokal)", url: "" },
  { file: "images/eksplorasi/pantai-kelapa-miring-2.jpeg", source: "Fotografer Kei (Original)", author: "Simfoni Evav", license: "CC BY (lokal)", url: "" },
  { file: "videos/eksplorasi/meti-timelapse.mp4", source: "Pexels", author: "Pexels (video id 2098988)", license: "Pexels License (free)", url: "https://www.pexels.com/video/ocean-waves-2098988/" },

  // === KATEGORI 4 — KULINER ===
  { file: "images/kuliner/kei_culinary_enbal.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_culinary_fish.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_culinary_sirsir.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_food_atmosfer.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_sagu_process.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_enbal_love.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_enbal_stik.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_enbal_bunga.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_pisang_enbal.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_ikan_colocolo.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_lat.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/kuliner/kei_mangrove_stick.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },

  // === KATEGORI 5 — SATWA & ALAM ===
  { file: "images/satwa/kei_endemic_bird.png", source: "Wikimedia Commons", author: "Wikimedia user (Red Bird-of-Paradise)", license: "CC BY-SA", url: "https://commons.wikimedia.org/wiki/File:Red_Bird-of-Paradise_0A2A2853.jpg" },
  { file: "images/satwa/kei_underwater.png", source: "Wikimedia Commons", author: "Wikimedia user (Moore Reef underwater ReefScape)", license: "CC BY-SA", url: "https://commons.wikimedia.org/wiki/File:Moore_Reef_underwater_ReefScape.jpg" },
  { file: "images/satwa/kei_reef_fish.png", source: "Wikimedia Commons", author: "Wikimedia user (Soft coral peach komodo)", license: "CC BY-SA", url: "https://commons.wikimedia.org/wiki/File:Soft_coral_peach_komodo.jpg" },
  { file: "images/satwa/kei_dolphin.png", source: "Wikimedia Commons", author: "Wikimedia user (Tursiops truncatus 01)", license: "CC BY-SA", url: "https://commons.wikimedia.org/wiki/File:Tursiops_truncatus_01.jpg" },
  { file: "images/satwa/kei_mangrove.png", source: "Wikimedia Commons", author: "Wikimedia user (Benoa Bali Indonesia-Mangrove-forest-01)", license: "CC BY-SA", url: "https://commons.wikimedia.org/wiki/File:Benoa_Bali_Indonesia-Mangrove-forest-01.jpg" },
  { file: "images/satwa/kei_coral.png", source: "Wikimedia Commons", author: "Wikimedia user", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/satwa/kei_seaturtle.png", source: "Wikimedia Commons", author: "Wikimedia user", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },
  { file: "images/satwa/kei_wildlife.png", source: "Wikimedia Commons", author: "Wikimedia user", license: "CC BY-SA", url: "https://commons.wikimedia.org/" },

  // === KATEGORI 6 — KETERHUBUNGAN & UMKM ===
  { file: "images/meti/kei_mosaic_1.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/meti/kei_mosaic_3.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/meti/kei_mosaic_4.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/meti/kei_mosaic_5.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/meti/kei_community_1.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/meti/kei_community_2.png", source: "Unsplash", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/umkm/kei_umkm_enbal_bunga_1.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_enbal_bunga_2.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_enbal_crispy_rumput_laut.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_enbal_kacang_1.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_enbal_kacang_2.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_enbal_stick_1.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_enbal_stick_2.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_enbal_stick_3.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_kacang_botol_1.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_kacang_botol_2.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_kerupuk_enbal_super.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_kue_kering_mocaf_makmur_1.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_kue_kering_mocaf_makmur_2.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_kue_kering_mocaf_saleha.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_piece_enbal.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },
  { file: "images/umkm/kei_umkm_tepung_mocaf.jpeg", source: "Fotografer Kei (Original)", author: "UMKM Kei", license: "CC BY (lokal)", url: "" },

  { file: "images/teknologi/kei_technology_hawear.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/teknologi/kei_technology_meti.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "images/teknologi/kei_technology_sasi.png", source: "Unsplash (representative)", author: "Unsplash", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },

  // === KATEGORI 7 — AUDIO, OG & IKON BRAND ===
  { file: "sounds/kei-waves.webm", source: "Freesound", author: "dobroide", license: "CC0 1.0 (public domain)", url: "https://freesound.org/people/dobroide/sounds/93647/" },
  { file: "images/og/simfoni-evav-og.jpg", source: "Unsplash", author: "kian zhang", license: "Unsplash License (free)", url: "https://images.unsplash.com/" },
  { file: "Kapal.svg", source: "Original (generated)", author: "Simfoni Evav", license: "CC0", url: "" },
  { file: "Logo Black.svg", source: "Original (brand)", author: "Simfoni Evav", license: "Proprietary", url: "" },
  { file: "Logo Color.svg", source: "Original (brand)", author: "Simfoni Evav", license: "Proprietary", url: "" },
  { file: "Logo White.svg", source: "Original (brand)", author: "Simfoni Evav", license: "Proprietary", url: "" },
  { file: "MAatahari.svg", source: "Original (generated)", author: "Simfoni Evav", license: "CC0", url: "" },
];
