// Data terpusat katalog UMKM Unggulan Kepulauan Kei.
// Dipindahkan dari BeritaUmkmSection agar dapat dipakai ulang di halaman
// /taste (section katalog UMKM) tanpa menduplikasi data (GRAND_DESIGN §4.10).
// Semua teks UI berbahasa Indonesia; nomor WhatsApp adalah placeholder
// (ganti dengan nomor riil sebelum production).

export type UmkmItem = {
  id: string;
  name: string;
  category: "Kuliner" | "Kerajinan" | "Oleh-oleh";
  location: string;
  rating: number;
  image: string;
  whatsapp: string;
  desc: string;
};

export const umkms: UmkmItem[] = [
  {
    id: "u1",
    name: "Rumah Enbal Mbak Yuli",
    category: "Kuliner",
    location: "Langgur, Kei Kecil",
    rating: 4.7,
    image: "/images/umkm/kei_umkm_enbal_kacang_1.jpeg",
    whatsapp: "6281234567890",
    desc: "Enbal ikan bakar bumbu khas Kei dengan paduan kacang yang gurih renyah, siap menemani meja makan keluarga.",
  },
  {
    id: "u2",
    name: "Tenun Kei Suster Maria",
    category: "Kerajinan",
    location: "Tual, Maluku Tenggara",
    rating: 4.9,
    image: "/images/meti/kei_mosaic_3.png",
    whatsapp: "6281234567891",
    desc: "Kain tenun kei bermotif warisan leluhur, dirajut tangan dengan benang alam yang kaya makna budaya.",
  },
  {
    id: "u3",
    name: "Oleh-oleh Khas Bumi Evav",
    category: "Oleh-oleh",
    location: "Ohoililir, Kei Kecil",
    rating: 4.6,
    image: "/images/umkm/kei_umkm_kacang_botol_1.jpeg",
    whatsapp: "6281234567892",
    desc: "Kacang botol khas Kei yang renyah dan tahan lama, oleh-oleh sempurna dari bumi Evav.",
  },
  {
    id: "u4",
    name: "Enbal Bunga Mbak Rina",
    category: "Kuliner",
    location: "Langgur, Kei Kecil",
    rating: 4.8,
    image: "/images/umkm/kei_umkm_enbal_bunga_1.jpeg",
    whatsapp: "6281234567893",
    desc: "Enbal berbentuk bunga dengan bumbu khas Kei yang harum, menyajikan keindahan rasa dalam setiap suapan.",
  },
  {
    id: "u5",
    name: "Enbal Bunga Khas Kei",
    category: "Kuliner",
    location: "Tual, Maluku Tenggara",
    rating: 4.5,
    image: "/images/umkm/kei_umkm_enbal_bunga_2.jpeg",
    whatsapp: "6281234567894",
    desc: "Variasi enbal bunga panggang yang lembut di dalam, renyah di luar, kaya cita rasa laut Kei.",
  },
  {
    id: "u6",
    name: "Crispy Rumput Laut Evav",
    category: "Kuliner",
    location: "Ohoililir, Kei Kecil",
    rating: 4.6,
    image: "/images/umkm/kei_umkm_enbal_crispy_rumput_laut.jpeg",
    whatsapp: "6281234567895",
    desc: "Camilan rumput laut kering yang crispy dan gurih, snack sehat langsung dari perairan Kei.",
  },
  {
    id: "u7",
    name: "Enbal Kacang Bundo",
    category: "Kuliner",
    location: "Langgur, Kei Kecil",
    rating: 4.7,
    image: "/images/umkm/kei_umkm_enbal_kacang_2.jpeg",
    whatsapp: "6281234567896",
    desc: "Enbal dengan taburan kacang panggang, paduan rasa laut dan gurih yang bikin ketagihan.",
  },
  {
    id: "u8",
    name: "Stick Enbal Rumah Kita",
    category: "Kuliner",
    location: "Tual, Maluku Tenggara",
    rating: 4.8,
    image: "/images/umkm/kei_umkm_enbal_stick_1.jpeg",
    whatsapp: "6281234567897",
    desc: "Enbal stik praktis yang renyah, camilan jalanan pinggir laut untuk dinikmati sambil duduk di pasir.",
  },
  {
    id: "u9",
    name: "Stick Enbal Mama Tonce",
    category: "Kuliner",
    location: "Ohoililir, Kei Kecil",
    rating: 4.6,
    image: "/images/umkm/kei_umkm_enbal_stick_2.jpeg",
    whatsapp: "6281234567898",
    desc: "Stik enbal rumahan dengan bumbu kei yang pas, camilan hangat khas keluarga pesisir.",
  },
  {
    id: "u10",
    name: "Stick Enbal Kei Prime",
    category: "Kuliner",
    location: "Langgur, Kei Kecil",
    rating: 4.5,
    image: "/images/umkm/kei_umkm_enbal_stick_3.jpeg",
    whatsapp: "6281234567899",
    desc: "Enbal stik premium dengan tekstur renyah merata, pilihan oleh-oleh laut yang elegan.",
  },
  {
    id: "u11",
    name: "Kacang Botol Makmur",
    category: "Oleh-oleh",
    location: "Tual, Maluku Tenggara",
    rating: 4.7,
    image: "/images/umkm/kei_umkm_kacang_botol_2.jpeg",
    whatsapp: "6281234567900",
    desc: "Kacang botol renyah kemasan rapi, oleh-oleh khas Kei yang awet dan mudah dibawa pulang.",
  },
  {
    id: "u12",
    name: "Kerupuk Enbal Super",
    category: "Kuliner",
    location: "Ohoililir, Kei Kecil",
    rating: 4.6,
    image: "/images/umkm/kei_umkm_enbal_super.jpeg",
    whatsapp: "6281234567901",
    desc: "Kerupuk enbal dengan aroma laut yang kuat, garing dan gurih untuk teman makan bersama.",
  },
  {
    id: "u13",
    name: "Kue Kering Mocaf Makmur",
    category: "Oleh-oleh",
    location: "Langgur, Kei Kecil",
    rating: 4.8,
    image: "/images/umkm/kei_umkm_kue_kering_mocaf_makmur_1.jpeg",
    whatsapp: "6281234567902",
    desc: "Kue kering dari tepung mocaf lokal, renyah dan ringan, oleh-oleh manis khas Kei.",
  },
  {
    id: "u14",
    name: "Kue Kering Mocaf Makmur 2",
    category: "Oleh-oleh",
    location: "Tual, Maluku Tenggara",
    rating: 4.7,
    image: "/images/umkm/kei_umkm_kue_kering_mocaf_makmur_2.jpeg",
    whatsapp: "6281234567903",
    desc: "Variasi kue kering mocaf dengan rasa khas, camilan manis yang awet untuk oleh-oleh.",
  },
  {
    id: "u15",
    name: "Kue Kering Mocaf Saleha",
    category: "Oleh-oleh",
    location: "Ohoililir, Kei Kecil",
    rating: 4.9,
    image: "/images/umkm/kei_umkm_kue_kering_mocaf_saleha.jpeg",
    whatsapp: "6281234567904",
    desc: "Kue kering mocaf rumahan dengan rasa autentik, favorit oleh-oleh dari dapur Kei.",
  },
  {
    id: "u16",
    name: "Piece Enbal & Tepung Mocaf",
    category: "Kuliner",
    location: "Langgur, Kei Kecil",
    rating: 4.6,
    image: "/images/umkm/kei_umkm_piece_enbal.jpeg",
    whatsapp: "6281234567905",
    desc: "Potongan enbal siap masak bersama tepung mocaf lokal, praktis untuk hidangan keluarga.",
  },
  {
    id: "u17",
    name: "Tepung Mocaf Bumi Evav",
    category: "Oleh-oleh",
    location: "Tual, Maluku Tenggara",
    rating: 4.7,
    image: "/images/umkm/kei_umkm_tepung_mocaf.jpeg",
    whatsapp: "6281234567906",
    desc: "Tepung mocaf dari singkong lokal bumi Evav, bahan dasar sehat pengganti terigu untuk kue khas Kei.",
  },
];
